### ISSUE TITLE
Error loading Song list!

### ISSUE THREAD

**Issue by pyhoon** [pyhoon/music-player-wpf-vb#1]
This error occur very likely is because the computer has no MS Access 2013 32bit installed which support accdb file extension or Microsoft.ACE.OLEDB.12.0.

**Comment by zspri** [comment]
I would recommend changing the database to a .mdf file.

**Comment by pyhoon** [comment]
Thanks for reply. You are free to modify the code. I shall change to .mdb format. This code was made for a course work.

**Comment by pyhoon** [comment]
This project is outdated and not maintained.
